#!/usr/bin/python
from datetime import datetime, timedelta
import subprocess
import time

# Name of testing branch
testing_name='testing'

# Name of production branch
production_name='production'

# Threshold of days between moving testing to production
days_between_promotion=4

# Find threshold date based on days between promotion
threshold_date = datetime.today() - timedelta(days=days_between_promotion)

def main():

    # Get list of updates to consider promoting
    cmd="/usr/local/reposado/repoutil --diff=" + testing_name + " " + production_name
    difftest = subprocess.check_output(cmd, shell=True).splitlines()

    # Initialize counter at second line to avoid Unique to 'testing':
    i=1

    # Loop through lines of output
    while i < len(difftest):
        # Define the line
        line=difftest[i]
        # Process until we get to a blank line or Unique to 'production'
        if "Unique to" not in line and line != '':
            # Define the date based on YYYY-MM-DD string
            line_date=datetime(*time.strptime(line[78:88], "%Y-%m-%d")[0:6])
            # Define the product ID, and strip out extra white space on the right
            product_id=line[0:16].rstrip()
            # If the date of the product is less than the threshold date...
            if line_date < threshold_date:
                # Add it to the production branch
                print "Adding %s to %s because %s is before %s" % (product_id, production_name, line_date, threshold_date)
                cmd="/usr/local/reposado/repoutil --add-product " + product_id + " " + production_name
                subprocess.call(cmd, shell=True)
            else:
                print "Keeping %s in %s because %s is still after %s" % (product_id, testing_name, line_date, threshold_date)
        # If we've gotten to a blank line, end the while loop
        else:
            break
        # Increase counter for while loop
        i += 1

if __name__ == '__main__':
    main()
